baseURL = 'https://minseong0609.github.io/'
languageCode = 'en'
title = 'MS의 Hugo blog'
theme = "DoIt"



name = "DoIt"
license = "MIT"
licenselink = "https://github.com/HEIGE-PCloud/DoIt/blob/main/LICENSE"
description = "A Clean, Elegant but Advanced Hugo Theme for Hugo."
homepage = "https://github.com/minseong0609"
demosite = "https://hugodoit.pages.dev"
tags = [
  "blog",
  "clean",
  "responsive",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized"
]

[author]
  name = "Minseong"
  homepage = "https://github.com/minseong0609"

[original]
  name = "Dillon"
  homepage = "https://dillonzq.com/"
  repo = "https://github.com/dillonzq/LoveIt/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.83.0"

[outputs]
  home = ["HTML", "RSS", "JSON"]


